version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: projeto_fia
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: projeto_fia
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: user123
      MB_DB_HOST: postgres